.PHONY: all

all: test_prispevok_pri_narodeni_dietata test_rodicovsky_prispevok test_pridavok_na_dieta test_prispevok_na_viac_sucasne_narodenych_deti test_prispevok_na_starostlivost test_tehotensky_prispevok test_tehotenske_stipendium test_materska_dovolenka test_pomoc_v_hmotnej_nudzi test_vyzivne test_nahradne_vyzivne test_otcovske test_prispevok_na_zvysenu_splatku_uveru test_prispevok_na_opatrovanie test_prispevok_na_osobnu_asistenciu test_prispevok_na_komenzaciu_zvysenych_nakladov_stravovanie test_prispevok_na_komenzaciu_zvysenych_nakladov_hygiena test_prispevok_na_komenzaciu_zvysenych_nakladov_vozidlo test_prispevok_na_komenzaciu_zvysenych_nakladov_pes test_nahrada_nakladov_spojenych_s_pohrebom test_pozostalostna_urazova_renta test_jednorazove_odskodnenie test_vdovsky_dochodok test_sirotsky_dochodok

test_prispevok_pri_narodeni_dietata:
	node tests/prispevok_pri_narodeni_dietata/test_prispevok_pri_narodeni_dietata.js

test_rodicovsky_prispevok:
	node tests/rodicovsky_prispevok/test_rodicovsky_prispevok.js

test_pridavok_na_dieta:
	node tests/pridavok_na_dieta/test_pridavok_na_dieta.js

test_prispevok_na_viac_sucasne_narodenych_deti:
	node tests/prispevok_na_viac_sucasne_narodenych_deti/test_prispevok_na_viac_sucasne_narodenych_deti.js

test_prispevok_na_starostlivost:
	node tests/prispevok_na_starostlivost/test_prispevok_na_starostlivost.js

test_tehotensky_prispevok:
	node tests/tehotensky_prispevok/test_tehotensky_prispevok.js

test_tehotenske_stipendium:
	node tests/tehotenske_stipendium/test_tehotenske_stipendium.js

test_materska_dovolenka:
	node tests/materska_dovolenka/test_materska_dovolenka.js

test_pomoc_v_hmotnej_nudzi:
	node tests/pomoc_v_hmotnej_nudzi/test_pomoc_v_hmotnej_nudzi.js

test_vyzivne:
	node tests/vyzivne/test_vyzivne.js

test_nahradne_vyzivne:
	node tests/nahradne_vyzivne/test_nahradne_vyzivne.js

test_otcovske:
	node tests/otcovske/test_otcovske.js

test_prispevok_na_zvysenu_splatku_uveru:
	node tests/prispevok_na_zvysenu_splatku_uveru/test_prispevok_na_zvysenu_splatku_uveru.js

test_prispevok_na_opatrovanie:
	node tests/prispevok_na_opatrovanie/test_prispevok_na_opatrovanie.js

test_prispevok_na_osobnu_asistenciu:
	node tests/prispevok_na_osobnu_asistenciu/test_prispevok_na_osobnu_asistenciu.js

test_prispevok_na_komenzaciu_zvysenych_nakladov_stravovanie:
	node tests/prispevok_na_komenzaciu_zvysenych_nakladov_stravovanie/test_prispevok_na_komenzaciu_zvysenych_nakladov_stravovanie.js

test_prispevok_na_komenzaciu_zvysenych_nakladov_hygiena:
	node tests/prispevok_na_komenzaciu_zvysenych_nakladov_hygiena/test_prispevok_na_komenzaciu_zvysenych_nakladov_hygiena.js

test_prispevok_na_komenzaciu_zvysenych_nakladov_vozidlo:
	node tests/prispevok_na_komenzaciu_zvysenych_nakladov_vozidlo/test_prispevok_na_komenzaciu_zvysenych_nakladov_vozidlo.js

test_prispevok_na_komenzaciu_zvysenych_nakladov_pes:
	node tests/prispevok_na_komenzaciu_zvysenych_nakladov_pes/test_prispevok_na_komenzaciu_zvysenych_nakladov_pes.js

test_nahrada_nakladov_spojenych_s_pohrebom:
	node tests/nahrada_nakladov_spojenych_s_pohrebom/test_nahrada_nakladov_spojenych_s_pohrebom.js

test_pozostalostna_urazova_renta:
	node tests/pozostalostna_urazova_renta/test_pozostalostna_urazova_renta.js

test_jednorazove_odskodnenie:
	node tests/jednorazove_odskodnenie/test_jednorazove_odskodnenie.js

test_vdovsky_dochodok:
	node tests/vdovsky_dochodok/test_vdovsky_dochodok.js

test_sirotsky_dochodok:
	node tests/sirotsky_dochodok/test_sirotsky_dochodok.js

test_prispevok_na_pohreb:
	node tests/prispevok_na_pohreb/test_prispevok_na_pohreb.js

